version: '3.8'

services:
  db:
    image: postgres:15
    container_name: postgres-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: prueba
    ports:
      - "5432:5432"
    networks:
      - develop

  flaskApi:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: eyeonu-api
    image: eyeonu-api  # Nombre personalizado para la imagen
    command: python app.py --test --ii
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      DATABASE_URL: "postgresql://postgres:postgres@db:5432/prueba"
    networks:
      - develop
    env_file:
      - .env

  # fletApp:
  #   build: ./myApp
  #   container_name: eyeonu-app
  #   image: eyeonu-app  # Nombre personalizado para la imagen
  #   command: flet run --android
  #   ports:
  #     - "3000:3000"
  #   depends_on:
  #     - flaskApi
  #   networks:
  #     - develop
  
networks:
  develop:
