"""Initial migration

Revision ID: 972feff7cc55
Revises: 
Create Date: 2024-07-26 23:05:12.194528

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '972feff7cc55'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('frame', schema=None) as batch_op:
        batch_op.add_column(sa.Column('raw_frame_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint('frame_rawFrameId_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'raw_frame', ['raw_frame_id'], ['id'])
        batch_op.drop_column('rawFrameId')

    with op.batch_alter_table('individual', schema=None) as batch_op:
        batch_op.add_column(sa.Column('collection_id', sa.String(), nullable=False))

    with op.batch_alter_table('raw_frame', schema=None) as batch_op:
        batch_op.alter_column('pixels',
               existing_type=postgresql.BYTEA(),
               nullable=False)
        batch_op.alter_column('creation_time',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)

    with op.batch_alter_table('sighting', schema=None) as batch_op:
        batch_op.add_column(sa.Column('collection_id', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('body_coordinates', sa.ARRAY(sa.Integer()), nullable=False))
        batch_op.add_column(sa.Column('face_coordinates', sa.ARRAY(sa.Integer()), nullable=False))
        batch_op.add_column(sa.Column('object_coordinates', sa.ARRAY(sa.Integer()), nullable=False))
        batch_op.add_column(sa.Column('is_read', sa.Boolean(), nullable=False))
        batch_op.drop_column('pixel_area')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sighting', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pixel_area', postgresql.BYTEA(), autoincrement=False, nullable=False))
        batch_op.drop_column('is_read')
        batch_op.drop_column('object_coordinates')
        batch_op.drop_column('face_coordinates')
        batch_op.drop_column('body_coordinates')
        batch_op.drop_column('collection_id')

    with op.batch_alter_table('raw_frame', schema=None) as batch_op:
        batch_op.alter_column('creation_time',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
        batch_op.alter_column('pixels',
               existing_type=postgresql.BYTEA(),
               nullable=True)

    with op.batch_alter_table('individual', schema=None) as batch_op:
        batch_op.drop_column('collection_id')

    with op.batch_alter_table('frame', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rawFrameId', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('frame_rawFrameId_fkey', 'raw_frame', ['rawFrameId'], ['id'])
        batch_op.drop_column('raw_frame_id')

    # ### end Alembic commands ###
